//Question and Answer array...
//  Pipe and cistern data start
const qstnAns = [
    {
      id: "01",
      question: "A cistern has two taps attached to it. Tap B can empty the cistern in 45 minutes. But Tap A can fill the cistern in just 30 minutes. Rohit started both taps unknowingly but realized his mistake after 30 minutes. He immediately closed Tap B. Now after this, in how much time will the cistern be filled?",
      a: "30 minutes",
      b: "45 minutes",
      c: "15 minutes",
      d: "20 minutes",
      answer: "d",
    },
    {
      id: "02",
      question: "Pipe R can empty a full tank in 30 hours. But two pipes P and Q can fill a tank in 15 hours and 10 hours respectively. Ram unknowingly opened all three taps. After 2 hours Shyam realized it and closed Pipe R. Due to this mistake how much time more would it take to fill the tank?",
      a: " 18 minutes",
      b: "24 minutes",
      c: "1 hour 20 minutes",
      d: "2 hours 15 minutes",
      answer: "b",
    },
    {
      id: "03",
      question: "A cistern is filled by Pipe A and Pipe B together in 2.4 hours. Pipe A alone can fill the cistern at the rate of 100 litres per hour. Pipe B alone can fill the cistern in 4 hours. What is the capacity of the cistern?",
      a: "1200 litres",
      b: "600 litres",
      c: "1000 litres",
      d: "500 litres",
      answer: "b",
    },
    {
      id: "04",
      question: "There is a leak at the bottom of a cistern. Due to this it takes 8 hours to fill the cistern. Had there not been a leak, it would take one hour less to fill the cistern. How much time does it take for the leak to completely empty the cistern?",
      a: "48 hours ",
      b: "55(1/3) hours",
      c: "56 hours",
      d: "15 hours",
      answer: "c",
    },
    {
      id: "05",
      question: "Tap P alone fills a cistern in 2 hours; while tap Q alone fills the same cistern in 3 hours. A new tap R is attached to the bottom of the cistern which can empty the completely filled cistern in 6 hours. Sunny started all three taps together at 9am. When will the tank be full?",
      a: "10.30 am",
      b: "11.15 am",
      c: "12 pm",
      d: "9.45 am",
      answer: "a",
    },
    {
      id: "06",
      question: "A cistern can be filled in 6 hours by taps P and Q. If tap R also joins them, then cistern is filled in 5 hours. Tap P can fill the cistern at twice the rate of tap Q. In what time tap Q and R fill the cistern?",
      a: "9.75 hours",
      b: "10. 90 hours",
      c: "11.25 hours",
      d: "12.90 hours", 
      answer: "c",
    },
    {
      id: "07",
      question: "A cistern is normally filled with water in 10 hours but takes 5 hours longer to fill because of a leak in its bottom. If the cistern is full, the leak will empty the cistern in",
      a: "20 hours",
      b: "40 hours",
      c: "50 hours",
      d: "30 hours", 
      answer: "d",
    },
    {
      id: "08",
      question: " A tank has three taps P, Q and R. Taps P and Q can fill the tank in 1.5 and 2 hours, respectively. Tap R can empty the completely filled tank in just half hour. Tap P is opened at 8 am, tap Q is opened at 9am and tap R is opened at 10 am. At what exact time will the tank be empty?",
      a: "12 pm",
      b: "1.25 pm",
      c: "12.12 pm",
      d: "12.28 pm",
      answer: "c",
    },
    {
      id: "09",
      question: "A pipe can fill a tank in 6 hours. Another pipe can empty the tank in 12 hours. If both pipes are opened simultaneously, the part of tank filled by both pipes in 1 hour is?",
      a:" 1/9 th part",
      b:"1/6 th part",
      c:" 1/12 th part",
      d:"1/3 rd part",
      answer: "c",
    },
    {
      id: "10",
      question: "A tap having diameter 'd' can empty a tank in 84 min. How long another tap having diameter '2d' take to empty the same tank?",
      a:" 21 minutes",
      b:"42 minutes",
      c:"168 minutes",
      d:"28 minutes",
      answer: "a",
    },
  //  Pipe and cistern data end
    
  //Probability data start
    {
      id: "11",
      question: "If three coins are tossed simultaneously, what is the probability of getting two heads together?",
      a:"3/8",
      b:"1/8",
      c:"5/8",
      d:"None of the above",
      answer: "a",
    },
    {
      id: "12",
      question: "The probability of winning the first prize in a lottery of a girl is 8/100. If the total of 6000 tickets are sold, then how many tickets the girl purchased?",
      a:"480",
      b:"750",
      c:"280",
      d:"None of the above",
      answer: "a",
    },
    {
      id: "13",
      question: " What is the probability of the random arrangement of letters in the word 'UNIVERSITY' and two I's should come together?",
      a:"1/7",
      b:"3/5",
      c:"1/5",
      d:"2/7",
      answer: "c",
    },
    {
      id: "14",
      question: "In class, 30% of students study Hindi, 45% study Maths, and 15% study both Hindi and Maths. If a student is randomly selected, what is the probability that he/she study Hindi or maths?",
      a:"1/5",
      b:"3/5",
      c:"2/5",
      d:"2/7",
      answer: "b",
    },
    {
      id: "15",
      question: "Using the digits 1, 2, 3, 4, and 5, a number having five digits is formed without any repetition. What is the probability that the number is divisible by 4?",
      a:"1/5",
      b:"2/5",
      c:"5/6",
      d:"3/5",
      answer: "a",
    },
    {
      id: "16",
      question: " The probability of randomly selecting a rotten apple is 0.18 from the heap of 900 apples. So, what is the number of rotten apples in a heap?",
      a:"162",
      b:"164",
      c:"136",
      d:"160",
      answer: "a",
    },
    {
      id: "17",
      question: "A card is drawn from a pack of 52 cards. What is the probability that it is a face card (King, Queen, and Jack only)?",
      a:"1/26",
      b:"2/13",
      c:"1/13",
      d:"3/13",
      answer: "d",
    },
    {
      id: "18",
      question: "A card is drawn from a pack of 52 cards. What is the probability of getting a queen card?",
      a:"1/26",
      b:"1/52",
      c:"3/13",
      d:"1/13",
      answer: "d",
    },
    {
      id: "19",
      question: " What will be the probability of losing a game if the winning probability is 0.3?",
      a:"0.5",
      b:"0.6",
      c:"0.7",
      d:"0.8",
      answer: "c",
    },
    {
      id: "20",
      question: "If three coins are tossed simultaneously, what is the probability of getting atmost two heads?  ",
      a:"7/8",
      b:"1/8",
      c:"5/8",
      d:"None of the above",
      answer: "a",
    },
    //  Probability data end
  
    //Problem on age data start
    {
      id: "21",
      question: "Sachin is younger than Rahul by 7 years.If their ages are in the respective ratio of 7:9, how old is Sachin?ill",
      a:"16 Years",
      b:"18 Years",
      c:"28 Years",
      d:"24.5 Years",
      answer: "d",
    },
    {
      id: "22",
      question: "At present the ratio between the ages of Arun and Deepak is 4:3.After 6 years,Arun's age will be 26 years.What is the age of Deepak at present?",
      a:"12 years",
      b:"15 Years",
      c:" 19 and half",
      d:"21 years",
      answer: "b",
    },
    {
      id: "23",
      question: "The sum of the present ages of a father and son is 60 years.Six years ago ,father's  age was five times the age of the son.After 6 years ,son's age will be:",
      a:"12 years",
      b:"14 Years",
      C:"18 Years",
      d:"20 years",
      answer: "d",
    },
    {
      id: "24",
      question: "Six years ago the ratio of the ages of Kunal and Sagar was 6:5.Four years hence,the ratio of their ages will be 11:10.what is Sagar's age at present?",
      a:"16 years",
      b:"Cannot be determined",
      c:" 18 Years",
      d:"20 years",
      answer: "a",
    },
    {
      id: "25",
      question: ".A man is 24 years older than his son. In two years,his age will be twice the age of his son.the present age of his son is: ",
      a:"16 years",
      b:"22 Years",
      c:"18 Years",
      d:"20 years",
      answer: "b",
    },
    {
      id: "26",
      question: "Present ages of Sameer and Anand are in the ratio of 5:4 respectively.Three years hence,the ratio of their ages will become 11:9 respectively.What is Anand's present age in years?",
      a:"24 ",
      b:"27 ",
      c:" 40",
      d:"Cannot be determined",
      answer: "a",
    },
    {
      id: "27",
      question: "A is two years older then B who is twice as old as C.If the total of the ages  of A,B and C be 27,the how old is B?",
      a:"7 ",
      b:"8 ",
      c:" 9",
      d:"10",
      answer: "d",
    },
    {
      id: "28",
      question: "A father said to his son,'I was as old as you are at the present at the time of your birth'.If the father's age is 38 years now,the son's age five years back was:",
      a:"14 years",
      b:"19 Years",
      c:" 33 Years",
      d:"38 years",
      answer: "a",
    },
    {
      id: "29",
      question: "The sum of ages of 5 childeren born at the intervals of 3 years each is 50 years.What is the age of the youngest child?",
      a:"4 years",
      b:"8 Years",
      c:" 10 Years",
      d:"None of these",
      answer: "a",
    },
    {
      id: "30",
      question: "Father is aged three times more than his son Ranit.After 8 years,he would be two and a half times of Ranit's age.After furter 8 years ,how many times would he be of Ranit's age?",
      a:"2 times",
       b:" 2(1/2) times",
      c:" 2(3/4) times",
      d:"3 times",
      answer: "a",
    },
    //  Problem on age data end
  
    //Profit and loss data start
    {
      id: "31",
      question: " A person sold a stove for Rs. 423 and incurred a loss of 6%. At what price would it be sold so as to earn a profit of 8%?",
      a:"Rs. 525",
      b:"Rs. 500",
      c:"Rs. 490",
      d:"Rs. 486",
      answer: "d",
    },
    {
      id: "32",
      question: " A fruit seller buys lemons at 2 for a rupee and sells then at 5 for three rupees. His gain percent is",
      a:"10%",
      b:"15%",
      c:"20%",
      d:"25%",
      answer: "c",
    },
    {
      id: "33",
      question: "A sells a car to B at 10% loss. If B sells it for Rs. 54000 and gains 20%, the cost price of the car for A was",
      a:"Rs. 25000",
      b:"Rs. 50000",
      c:"Rs. 37500",
      d:"Rs. 60000",
      answer: "b",
    },
    {
      id: "34",
      question: " Ramesh sold a statue for a price 25% higher than the original price of the statue. He had however bought the statue at 20% discount on the original price. With the profit of Rs. 2025, find the original price of the statue.",
      a:"Rs. 6000",
      b:"Rs. 7500",
      c:"Rs. 3500",
      d:"Rs. 4500",
      answer: "d",
    },
    {
      id: "35",
      question: "If selling price of 40 articles is equal to cost price of 50 articles, the loss or gain percent is",
      a:"25% loss",
      b:"20% loss",
      c:"25% gain",
      d:"20% gain",
      answer: "c",
    },
    {
      id: "36",
      question: " Two bicycles were sold for Rs. 3990 each, gaining 5% on one and losing 5% on the other. The gain or loss percent on the whole transaction is",
      a:"Neither gain nor loss",
      b:"2.5% gain",
      c:"2.5% loss",
      d:"0.25% loss",
      answer: "d",
    },
    {
      id: "37",
      question: " The ratio of cost price and selling price is 4:5. The profit percent is",

      a:"10%",
      b:"20%",
      c:"25%",
      d:"30%",
      answer: "c",
    },
    {
      id: "38",
      question: "If a person sells a ‘sari’ for Rs. 5200, making a profit of 30%, then the cost price of the sari is",
      a:"Rs. 4420",
      b:"Rs. 4000",
      c:"Rs. 3900",
      d:"Rs. 3800",
      answer: "b",
    },
    {
      id: "39",
      question: "A shopkeeper earns a profit of 15% after selling a book at 20% discount on the printed price. The ratio of the cost price and printed price of the book is?",
      a:"20:23",
      b:"23:20",
      c:"16:23",
      d:"23:16",
      answer: "c",
    },
    {
      id: "40",
      question: "Simran bought pet food worth Rs. 56000. She then sold 1/3rd of it incurring a loss of 40%. What profit she must earn on rest of the supplies to nullify this loss?",
      a:"25%",
      b:"20%",
      c:"45%",
      d:"50%",
      
      answer: "b",
    },
    // Profit and loss data end
  
  
  ];
  